name: Selftest

on:
  release:
    types: [prereleased, released]

jobs:
  selftest:
    name: Selftest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Echo generated version
        run: echo $SEMVER
